# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestResetpassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_resetpassword(self):
    self.driver.get("https://dazhadazha.pythonanywhere.com/")
    self.driver.set_window_size(1920, 1040)
    self.driver.find_element(By.LINK_TEXT, "Forgot password?").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test@qq.com")
    self.driver.find_element(By.ID, "answer").send_keys("test")
    self.driver.find_element(By.ID, "password").send_keys("thisisnewpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(9)").click()
  
